using Silk.NET.SDL;

namespace Crimson.Platform;

internal class SdlUtils
{
    public static Sdl SDL;

    static SdlUtils()
    {
        SDL = Sdl.GetApi();
    }

    public static Key KeycodeToKey(KeyCode keycode)
    {
        return keycode switch
        {
            KeyCode.KReturn => Key.Return,
            KeyCode.KEscape => Key.Escape,
            KeyCode.KBackspace => Key.Backspace,
            KeyCode.KTab => Key.Tab,
            KeyCode.KSpace => Key.Space,
            KeyCode.KHash => Key.Hash,
            KeyCode.KQuote => Key.Apostrophe,
            KeyCode.KComma => Key.Comma,
            KeyCode.KMinus => Key.Minus,
            KeyCode.KPeriod => Key.Period,
            KeyCode.KSlash => Key.ForwardSlash,
            KeyCode.K0 => Key.Num0,
            KeyCode.K1 => Key.Num1,
            KeyCode.K2 => Key.Num2,
            KeyCode.K3 => Key.Num3,
            KeyCode.K4 => Key.Num4,
            KeyCode.K5 => Key.Num5,
            KeyCode.K6 => Key.Num6,
            KeyCode.K7 => Key.Num7,
            KeyCode.K8 => Key.Num8,
            KeyCode.K9 => Key.Num9,
            KeyCode.KSemicolon => Key.Semicolon,
            KeyCode.KEquals => Key.Equals,
            KeyCode.KLeftbracket => Key.LeftBracket,
            KeyCode.KRightbracket => Key.RightBracket,
            KeyCode.KBackslash => Key.Backslash,
            KeyCode.KBackquote => Key.Backquote,
            KeyCode.KA => Key.A,
            KeyCode.KB => Key.B,
            KeyCode.KC => Key.C,
            KeyCode.KD => Key.D,
            KeyCode.KE => Key.E,
            KeyCode.KF => Key.F,
            KeyCode.KG => Key.G,
            KeyCode.KH => Key.H,
            KeyCode.KI => Key.I,
            KeyCode.KJ => Key.J,
            KeyCode.KK => Key.K,
            KeyCode.KL => Key.L,
            KeyCode.KM => Key.M,
            KeyCode.KN => Key.N,
            KeyCode.KO => Key.O,
            KeyCode.KP => Key.P,
            KeyCode.KQ => Key.Q,
            KeyCode.KR => Key.R,
            KeyCode.KS => Key.S,
            KeyCode.KT => Key.T,
            KeyCode.KU => Key.U,
            KeyCode.KV => Key.V,
            KeyCode.KW => Key.W,
            KeyCode.KX => Key.X,
            KeyCode.KY => Key.Y,
            KeyCode.KZ => Key.Z,
            KeyCode.KDelete => Key.Delete,
            KeyCode.KCapslock => Key.CapsLock,
            KeyCode.KF1 => Key.F1,
            KeyCode.KF2 => Key.F2,
            KeyCode.KF3 => Key.F3,
            KeyCode.KF4 => Key.F4,
            KeyCode.KF5 => Key.F5,
            KeyCode.KF6 => Key.F6,
            KeyCode.KF7 => Key.F7,
            KeyCode.KF8 => Key.F8,
            KeyCode.KF9 => Key.F9,
            KeyCode.KF10 => Key.F10,
            KeyCode.KF11 => Key.F11,
            KeyCode.KF12 => Key.F12,
            KeyCode.KF13 => Key.F13,
            KeyCode.KF14 => Key.F14,
            KeyCode.KF15 => Key.F15,
            KeyCode.KF16 => Key.F16,
            KeyCode.KF17 => Key.F17,
            KeyCode.KF18 => Key.F18,
            KeyCode.KF19 => Key.F19,
            KeyCode.KF20 => Key.F20,
            KeyCode.KF21 => Key.F21,
            KeyCode.KF22 => Key.F22,
            KeyCode.KF23 => Key.F23,
            KeyCode.KF24 => Key.F24,
            KeyCode.KPrintscreen => Key.PrintScreen,
            KeyCode.KScrolllock => Key.ScrollLock,
            KeyCode.KPause => Key.Pause,
            KeyCode.KInsert => Key.Insert,
            KeyCode.KHome => Key.Home,
            KeyCode.KEnd => Key.End,
            KeyCode.KPageup => Key.PageUp,
            KeyCode.KPagedown => Key.PageDown,
            KeyCode.KRight => Key.Right,
            KeyCode.KLeft => Key.Left,
            KeyCode.KUp => Key.Up,
            KeyCode.KDown => Key.Down,
            KeyCode.KNumlockclear => Key.NumLock,
            KeyCode.KKPDivide => Key.KeypadDivide,
            KeyCode.KKPMultiply => Key.KeypadMultiply,
            KeyCode.KKPMinus => Key.KeypadSubtract,
            KeyCode.KKPPlus => Key.KeypadAdd,
            KeyCode.KKPEnter => Key.KeypadEnter,
            KeyCode.KKPDecimal => Key.KeypadDecimal,
            KeyCode.KKPEquals => Key.KeypadEqual,
            KeyCode.KKP0 => Key.Keypad0,
            KeyCode.KKP1 => Key.Keypad1,
            KeyCode.KKP2 => Key.Keypad2,
            KeyCode.KKP3 => Key.Keypad3,
            KeyCode.KKP4 => Key.Keypad4,
            KeyCode.KKP5 => Key.Keypad5,
            KeyCode.KKP6 => Key.Keypad6,
            KeyCode.KKP7 => Key.Keypad7,
            KeyCode.KKP8 => Key.Keypad8,
            KeyCode.KKP9 => Key.Keypad9,
            KeyCode.KMenu => Key.Menu,
            KeyCode.KLctrl => Key.LeftControl,
            KeyCode.KRctrl => Key.RightControl,
            KeyCode.KLalt => Key.LeftAlt,
            KeyCode.KRalt => Key.RightAlt,
            KeyCode.KLshift => Key.LeftShift,
            KeyCode.KRshift => Key.RightShift,
            KeyCode.KLgui => Key.LeftSuper,
            KeyCode.KRgui => Key.RightSuper,
            _ => Key.Unknown
        };
    }

    public static MouseButton ButtonIndexToButton(byte button)
    {
        return (MouseButton) button;
    }
}